security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    issei: { password: 'hogehoge', roles: ROLE_USER }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            provider:  in_memory
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout

    access_control:
        - { path: login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,    role: ROLE_USER }
